name: Go Tests

on:
  push:
    branches: master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Build libcodex
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake curl git rustc cargo
          make update
          make libcodex
          go build -o codex-go examples/golang/codex.go

      - name: Go test
        env:
          CGO_ENABLED: 1
        run: go test ./...